### PR TITLE
Create pt.json

### PR DESCRIPTION
**Pull request by ViPeR5000**
add portuguese language in lokalise pls

### CODE REVIEW

**Comment by astrandb** [comment]
Done!
Your translations will be included in next release of the integration.

**Comment by astrandb** [comment]
@ViPeR5000 The portuguese translations are still empty in Lokalise. Are you interested in contributing?

**Comment by ViPeR5000** [comment]
> @ViPeR5000 The portuguese translations are still empty in Lokalise. Are you interested in contributing?

yes but...No access to resource

**Comment by astrandb** [comment]
Sorry, should work now.

**Pull request closed without merging**
